# Generated by Django 6.0.1 on 2026-02-05 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhomgis', '0003_warehouse_base_fee_warehouse_fee_per_km_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.TextField(verbose_name='Địa chỉ giao'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.IntegerField(default=0, verbose_name='Tổng tiền (Hàng + Ship)'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='base_fee',
            field=models.IntegerField(default=15000, verbose_name='Phí cố định (VNĐ)'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='fee_per_km',
            field=models.IntegerField(default=5000, verbose_name='Phí mỗi KM (VNĐ)'),
        ),
    ]
