# Generated by Django 6.0.2 on 2026-04-16 20:47

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Giới thiệu về KINGMATE', max_length=255, verbose_name='Tiêu đề chính')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên danh mục')),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên kho hàng')),
                ('address', models.CharField(max_length=500, verbose_name='Địa chỉ')),
                ('latitude', models.FloatField(verbose_name='Vĩ độ')),
                ('longitude', models.FloatField(verbose_name='Kinh độ')),
                ('base_fee', models.IntegerField(default=15000, verbose_name='Phí cố định (VNĐ)')),
                ('fee_per_km', models.IntegerField(default=5000, verbose_name='Phí mỗi KM (VNĐ)')),
            ],
        ),
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tiêu đề hộp (Ví dụ: Sứ mệnh)')),
                ('content', models.TextField(verbose_name='Nội dung hộp')),
                ('order', models.IntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='nhomgis.aboutpage')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Số điện thoại')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Địa chỉ cụ thể')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Vĩ độ')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Kinh độ')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đặt')),
                ('shipping_fee', models.IntegerField(default=0, verbose_name='Phí vận chuyển')),
                ('total_amount', models.IntegerField(default=0, verbose_name='Tổng tiền (Hàng + Ship)')),
                ('status', models.CharField(choices=[('CHỜ XÁC NHẬN', 'Chờ xác nhận'), ('ĐANG GIAO', 'Đang giao'), ('ĐÃ GIAO', 'Đã giao'), ('ĐÃ HỦY', 'Đã hủy')], default='CHỜ XÁC NHẬN', max_length=50)),
                ('shipping_address', models.TextField(verbose_name='Địa chỉ giao')),
                ('customer_lat', models.FloatField(blank=True, null=True, verbose_name='Vĩ độ khách')),
                ('customer_lon', models.FloatField(blank=True, null=True, verbose_name='Kinh độ khách')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Khách hàng')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề')),
                ('content', models.TextField(verbose_name='Nội dung')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='Ảnh bìa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_comments', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='nhomgis.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='nhomgis.post')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên sản phẩm')),
                ('price', models.IntegerField(verbose_name='Giá bán')),
                ('unit', models.CharField(max_length=50, verbose_name='Đơn vị tính')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Mô tả')),
                ('stock_quantity', models.IntegerField(default=0, verbose_name='Tồn kho')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Ảnh chính')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nhomgis.category', verbose_name='Danh mục')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('price_at_purchase', models.IntegerField(verbose_name='Giá lúc mua')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='nhomgis.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nhomgis.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_gallery/', verbose_name='Ảnh phụ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='nhomgis.product')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('IMPORT', 'Nhập hàng'), ('EXPORT', 'Xuất hàng')], max_length=10, verbose_name='Loại giao dịch')),
                ('quantity', models.PositiveIntegerField(verbose_name='Số lượng')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Ngày thực hiện')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người thực hiện')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nhomgis.product', verbose_name='Sản phẩm')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nhomgis.warehouse', verbose_name='Kho hàng')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(default=5, verbose_name='Số sao (1-5)')),
                ('comment', models.TextField(verbose_name='Bình luận')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='nhomgis.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'product')},
            },
        ),
        migrations.CreateModel(
            name='StoreReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(default=5, verbose_name='Số sao (1-5)')),
                ('comment', models.TextField(verbose_name='Nhận xét')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user',)},
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='Số lượng tồn tại kho')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='nhomgis.product', verbose_name='Sản phẩm')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='nhomgis.warehouse', verbose_name='Kho hàng')),
            ],
            options={
                'unique_together': {('warehouse', 'product')},
            },
        ),
    ]
