# Generated by Django 6.0.1 on 2026-02-04 02:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhomgis', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên danh mục')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đặt')),
                ('total_amount', models.IntegerField(default=0, verbose_name='Tổng tiền hàng')),
                ('shipping_fee', models.IntegerField(default=0, verbose_name='Phí vận chuyển')),
                ('status', models.CharField(choices=[('CHỜ XÁC NHẬN', 'Chờ xác nhận'), ('ĐANG GIAO', 'Đang giao'), ('ĐÃ GIAO', 'Đã giao'), ('ĐÃ HỦY', 'Đã hủy')], default='CHỜ XÁC NHẬN', max_length=50)),
                ('shipping_address', models.CharField(max_length=255, verbose_name='Địa chỉ giao')),
                ('customer_lat', models.FloatField(blank=True, null=True, verbose_name='Vĩ độ khách')),
                ('customer_lon', models.FloatField(blank=True, null=True, verbose_name='Kinh độ khách')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Khách hàng')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('price_at_purchase', models.IntegerField(verbose_name='Giá lúc mua')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='nhomgis.order')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên sản phẩm')),
                ('price', models.IntegerField(verbose_name='Giá bán')),
                ('unit', models.CharField(max_length=50, verbose_name='Đơn vị tính')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('stock_quantity', models.IntegerField(default=0, verbose_name='Tồn kho')),
                ('image_url', models.CharField(blank=True, max_length=500, verbose_name='Link ảnh')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nhomgis.category', verbose_name='Danh mục')),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên kho')),
                ('address', models.CharField(max_length=200, verbose_name='Địa chỉ')),
                ('latitude', models.FloatField(verbose_name='Vĩ độ')),
                ('longitude', models.FloatField(verbose_name='Kinh độ')),
            ],
        ),
        migrations.DeleteModel(
            name='TodoItem',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nhomgis.product'),
        ),
    ]
