# Generated by Django 6.0.2 on 2026-04-16 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhomgis', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutsection',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='icon_class',
            field=models.CharField(blank=True, help_text='VD: bi-truck, bi-shield-check', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='section_type',
            field=models.CharField(choices=[('TEXT', 'Văn bản thường'), ('FEATURE', 'Tính năng (Có Icon)'), ('CONTACT', 'Khối Liên hệ')], default='TEXT', max_length=10),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Nội dung chi tiết'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='heading',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tiêu đề khối'),
        ),
    ]
