# Generated by Django 6.0.2 on 2026-04-16 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhomgis', '0002_alter_aboutsection_options_aboutsection_icon_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutsection',
            name='text_align',
            field=models.CharField(choices=[('text-start', 'Căn trái'), ('text-center', 'Căn giữa'), ('text-end', 'Căn phải'), ('text-justify', 'Căn đều')], default='text-start', max_length=20),
        ),
    ]
