# Generated by Django 6.0.2 on 2026-02-04 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhomgis', '0002_category_order_orderitem_product_warehouse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='base_fee',
            field=models.FloatField(default=15000, verbose_name='Phí cố định (VNĐ)'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='fee_per_km',
            field=models.FloatField(default=5000, verbose_name='Phí mỗi KM (VNĐ)'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='address',
            field=models.CharField(max_length=500, verbose_name='Địa chỉ'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Tên kho hàng'),
        ),
    ]
