# Generated by Django 6.0.2 on 2026-04-16 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhomgis', '0003_aboutsection_text_align'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorytransaction',
            name='batch_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Mã lô/phiếu'),
        ),
    ]
