# Generated by Django 6.0.2 on 2026-04-17 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhomgis', '0004_inventorytransaction_batch_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nhomgis.warehouse', verbose_name='Kho xuất hàng'),
        ),
    ]
