# Generated by Django 6.0.2 on 2026-04-17 08:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhomgis', '0005_order_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Số điện thoại không hợp lệ. Vui lòng nhập đúng 10 chữ số.', regex='^\\d{10}$')], verbose_name='Số điện thoại'),
        ),
    ]
