# Generated by Django 6.0.2 on 2026-04-15 00:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhomgis', '0006_post_author_storereview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('IMPORT', 'Nhập hàng'), ('EXPORT', 'Xuất hàng')], max_length=10, verbose_name='Loại giao dịch')),
                ('quantity', models.PositiveIntegerField(verbose_name='Số lượng')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Ngày thực hiện')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nhomgis.product', verbose_name='Sản phẩm')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người thực hiện')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nhomgis.warehouse', verbose_name='Kho hàng')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='Số lượng tồn tại kho')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='nhomgis.product', verbose_name='Sản phẩm')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='nhomgis.warehouse', verbose_name='Kho hàng')),
            ],
            options={
                'unique_together': {('warehouse', 'product')},
            },
        ),
    ]
