# Generated by Django 6.0.2 on 2026-04-15 01:54

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nhomgis', '0007_inventorytransaction_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Mô tả'),
        ),
    ]
