# Generated by Django 6.0.2 on 2026-04-15 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhomgis', '0009_customerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Vĩ độ'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Kinh độ'),
        ),
    ]
